import { z } from 'zod';
export const CampaignDataSchema = z.object({
    date: z.string(),
    campaignName: z.string(),
    campaignID: z.string(),
    landingPageURL: z.string().url(),
    trafficSource: z.string(),
    utmSource: z.string(),
    utmMedium: z.string(),
    deviceType: z.enum(['Desktop', 'Mobile', 'Tablet']),
    creativeID: z.string(),
    creativeName: z.string(),
    creativeType: z.enum(['Image', 'Video', 'Text']),
    sessions: z.number(),
    users: z.number(),
    newUsers: z.number(),
    bounceRate: z.number(),
    engagementRate: z.number(),
    avgTimeOnPage: z.number(),
    scrollDepth: z.number(),
    ctaClicks: z.number(),
    formViews: z.number(),
    formStarters: z.number(),
    formCompletions: z.number(),
    conversionCount: z.number(),
    conversionRate: z.number(),
    costPerSession: z.number(),
    costPerConversion: z.number(),
    cac: z.number(),
    leadToSQL: z.number(),
    sqlToOpportunity: z.number(),
});
//# sourceMappingURL=campaign-data.schema.js.map