import { z } from 'zod';
export declare const CampaignDataSchema: z.ZodObject<{
    date: z.ZodString;
    campaignName: z.ZodString;
    campaignID: z.ZodString;
    landingPageURL: z.ZodString;
    trafficSource: z.ZodString;
    utmSource: z.ZodString;
    utmMedium: z.ZodString;
    deviceType: z.ZodEnum<["Desktop", "Mobile", "Tablet"]>;
    creativeID: z.ZodString;
    creativeName: z.ZodString;
    creativeType: z.ZodEnum<["Image", "Video", "Text"]>;
    sessions: z.ZodNumber;
    users: z.ZodNumber;
    newUsers: z.ZodNumber;
    bounceRate: z.ZodNumber;
    engagementRate: z.ZodNumber;
    avgTimeOnPage: z.ZodNumber;
    scrollDepth: z.ZodNumber;
    ctaClicks: z.ZodNumber;
    formViews: z.ZodNumber;
    formStarters: z.ZodNumber;
    formCompletions: z.ZodNumber;
    conversionCount: z.ZodNumber;
    conversionRate: z.ZodNumber;
    costPerSession: z.ZodNumber;
    costPerConversion: z.ZodNumber;
    cac: z.ZodNumber;
    leadToSQL: z.ZodNumber;
    sqlToOpportunity: z.ZodNumber;
}, "strip", z.ZodTypeAny, {
    date: string;
    campaignName: string;
    campaignID: string;
    landingPageURL: string;
    trafficSource: string;
    utmSource: string;
    utmMedium: string;
    deviceType: "Desktop" | "Mobile" | "Tablet";
    creativeID: string;
    creativeName: string;
    creativeType: "Image" | "Video" | "Text";
    sessions: number;
    users: number;
    newUsers: number;
    bounceRate: number;
    engagementRate: number;
    avgTimeOnPage: number;
    scrollDepth: number;
    ctaClicks: number;
    formViews: number;
    formStarters: number;
    formCompletions: number;
    conversionCount: number;
    conversionRate: number;
    costPerSession: number;
    costPerConversion: number;
    cac: number;
    leadToSQL: number;
    sqlToOpportunity: number;
}, {
    date: string;
    campaignName: string;
    campaignID: string;
    landingPageURL: string;
    trafficSource: string;
    utmSource: string;
    utmMedium: string;
    deviceType: "Desktop" | "Mobile" | "Tablet";
    creativeID: string;
    creativeName: string;
    creativeType: "Image" | "Video" | "Text";
    sessions: number;
    users: number;
    newUsers: number;
    bounceRate: number;
    engagementRate: number;
    avgTimeOnPage: number;
    scrollDepth: number;
    ctaClicks: number;
    formViews: number;
    formStarters: number;
    formCompletions: number;
    conversionCount: number;
    conversionRate: number;
    costPerSession: number;
    costPerConversion: number;
    cac: number;
    leadToSQL: number;
    sqlToOpportunity: number;
}>;
export type CampaignData = z.infer<typeof CampaignDataSchema>;
//# sourceMappingURL=campaign-data.schema.d.ts.map